import delay from './delay'

const neighbourhoods = [
  {district:1, name:'حصاربوعلی' },
  {district:1, name:'فرمانیه' },
  {district:1, name:'اوین' },
  {district:1, name:'درکه' },
  {district:1, name:'زعفرانیه' },
  {district:1, name:'محمودیه' },
  {district:1, name:'ولنجک' },
  {district:1, name:'امام زاده قاسم (ع)' },
  {district:1, name:'دربند' },
  {district:1, name:'گلابدره' },
  {district:1, name:'جماران' },
  {district:1, name:'دزاشیب' },
  {district:1, name:'نیاوران' },
  {district:1, name:'اراج' },
  {district:1, name:'کاشانک' },
  {district:1, name:'شهرک دانشگاه' },
  {district:1, name:'شهرک نفت' },
  {district:1, name:'دارآباد' },
  {district:1, name:'باغ فردوس' },
  {district:1, name:'تجریش' },
  {district:1, name:'قیطریه' },
  {district:1, name:'چیذر' },
  {district:1, name:'حکمت' },
  {district:1, name:'ازگل' },
  {district:1, name:'سوهانک' },
  {district:1, name:'شهید محلاتی' },
  {district:1, name:'اتوبان امام علی' },
  {district:1, name:'اتوبان صدر' },
  {district:1, name:'اقدسیه' },
  {district:1, name:'الهیه – فرشته' },
  {district:1, name:'اندرزگو' },
  {district:1, name:'بلوار ارتش' },
  {district:1, name:'پارک وی' },
  {district:1, name:'تجریش' },
  {district:1, name:'جمشیدیه' },
  {district:1, name:'دیباجی' },
  {district:1, name:'سعدآباد' },
  {district:1, name:'صاحبقرانیه' },
  {district:1, name:'فرمانیه' },
  {district:1, name:'قیطریه' },
  {district:1, name:'محمودیه' },
  {district:1, name:'مقدس اردبیلی' },
  {district:1, name:'مینی سیتی' },
  {district:1, name:'نوبنیاد' },
  {district:1, name:'ولیعصر' },
  {district:1, name:'کاشانک' },
  {district:1, name:'کامرانیه' },

  {district:2, name:'بوعلی'},
  {district:2, name:'سعادت آباد'},
  {district:2, name:'مدیریت'},
  {district:2, name:'کوهسار'},
  {district:2, name:'پونک'},
  {district:2, name:'شهید چوب تراش'},
  {district:2, name:'شهید خرم رودی'},
  {district:2, name:'صادقیه شمالی شهرک هما'},
  {district:2, name:'صادقیه'},
  {district:2, name:'شهرآرا'},
  {district:2, name:'کوی نصر'},
  {district:2, name:'پردیسان'},
  {district:2, name:'شهرک آزمایش'},
  {district:2, name:'تهران ویلا'},
  {district:2, name:'برق آلستوم'},
  {district:2, name:'تیموری'},
  {district:2, name:'طرشت'},
  {district:2, name:'همایونشهر'},
  {district:2, name:'توحید'},
  {district:2, name:'زنجان'},
  {district:2, name:'شادمهر'},
  {district:2, name:'ایوانک'},
  {district:2, name:'دریا'},
  {district:2, name:'شهرک قدس'},
  {district:2, name:'آسمانها'},
  {district:2, name:'درختی'},
  {district:2, name:'فرحزاد'},
  {district:2, name:'مخابرات'},
  {district:2, name:'پرواز'},
  {district:2, name:'آزادی'},
  {district:2, name:'اتوبان حکیم'},
  {district:2, name:'اتوبان شیخ فضل اله نوری'},
  {district:2, name:'اتوبان محمد علی جناح'},
  {district:2, name:'اتوبان نیایش'},
  {district:2, name:'اتوبان یادگار امام'},
  {district:2, name:'بهبودی'},
  {district:2, name:'جلال آل احمد'},
  {district:2, name:'خوش شمالی'},
  {district:2, name:'ستارخان'},
  {district:2, name:'شادمان'},
  {district:2, name:'شهرک ژاندارمری'},
  {district:2, name:'شهرک غرب'},
  {district:2, name:'گیشا'},
  {district:2, name:'مترو شریف'},
  {district:2, name:'مرزداران'},

  {district:3, name:'آرارات'},
  {district:3, name:'ونک'},
  {district:3, name:'امانیه'},
  {district:3, name:'زرگنده'},
  {district:3, name:'درب دوم'},
  {district:3, name:'رستم آباد و اختیاریه'},
  {district:3, name:'داودیه'},
  {district:3, name:'سید خندان'},
  {district:3, name:'دروس'},
  {district:3, name:'قبا'},
  {district:3, name:'قلهک'},
  {district:3, name:'کاوسیه'},
  {district:3, name:'اختیاریه'},
  {district:3, name:'پاسداران'},
  {district:3, name:'جردن'},
  {district:3, name:'جلفا'},
  {district:3, name:'خواجه عبداله'},
  {district:3, name:'دولت ( کلاهدوز )'},
  {district:3, name:'شیخ بهایی'},
  {district:3, name:'شیراز'},
  {district:3, name:'ظفر'},
  {district:3, name:'ملاصدرا'},
  {district:3, name:'میدان کتابی'},
  {district:3, name:'میرداماد'},
  {district:3, name:'ولیعصر(بین پارک وی ونیایش)'},

  {district:4, name:'مهران'},
  {district:4, name:'کاظم آباد'},
  {district:4, name:'کوهک'},
  {district:4, name:'مجیدیه و شمس آباد'},
  {district:4, name:'پاسداران و ضرابخانه'},
  {district:4, name:'حسین آباد و مبارک آباد'},
  {district:4, name:'شیان و لویزان'},
  {district:4, name:'علم و صنعت'},
  {district:4, name:'نارمک'},
  {district:4, name:'تهرانپارس غربی'},
  {district:4, name:'جوادیه'},
  {district:4, name:'خاک سفید'},
  {district:4, name:'تهرانپارس شرقی'},
  {district:4, name:'قاسم آباد و ده نارمک'},
  {district:4, name:'اوقاف'},
  {district:4, name:'شمیران نو'},
  {district:4, name:'حکیمیه'},
  {district:4, name:'قنات کوثر'},
  {district:4, name:'کوهسار'},
  {district:4, name:'مجید آباد'},
  {district:4, name:'اتوبان بابایی'},
  {district:4, name:'اتوبان باقری'},
  {district:4, name:'اتوبان صیاد شیرازی'},
  {district:4, name:'بنی هاشم'},
  {district:4, name:'پلیس'},
  {district:4, name:'دلاوران'},
  {district:4, name:'رسالت'},
  {district:4, name:'سراج'},
  {district:4, name:'شمس آباد'},
  {district:4, name:'شهدا'},
  {district:4, name:'صیاد شیرازی'},
  {district:4, name:'علم وصنعت'},
  {district:4, name:'فرجام'},
  {district:4, name:'لویزان'},
  {district:4, name:'میدان ملت'},
  {district:4, name:'هروی'},
  {district:4, name:'هنگام'},

  {district:5, name:'شهران جنوبی'},
  {district:5, name:'شهران شمالی'},
  {district:5, name:'شهرزیبا'},
  {district:5, name:'اندیشه'},
  {district:5, name:'بهاران'},
  {district:5, name:'کن'},
  {district:5, name:'المهدی'},
  {district:5, name:'باغ فیض'},
  {district:5, name:'پونک جنوبی'},
  {district:5, name:'پونک شمالی'},
  {district:5, name:'حصارک'},
  {district:5, name:'شهرک نفت'},
  {district:5, name:'کوهسار'},
  {district:5, name:'مرادآباد'},
  {district:5, name:'پرواز'},
  {district:5, name:'سازمان برنامه جنوبی'},
  {district:5, name:'سازمان برنامه شمالی'},
  {district:5, name:'ارم'},
  {district:5, name:'سازمان آب'},
  {district:5, name:'اباذر'},
  {district:5, name:'فردوس'},
  {district:5, name:'مهران'},
  {district:5, name:'اکباتان'},
  {district:5, name:'بیمه'},
  {district:5, name:'آپادانا'},
  {district:5, name:'جنت آباد جنوبی'},
  {district:5, name:'جنت آباد شمالی'},
  {district:5, name:'جنت آباد مرکزی'},
  {district:5, name:'شاهین'},
  {district:5, name:'آیت الله کاشانی'},
  {district:5, name:'اشرفی اصفهانی'},
  {district:5, name:'ایران زمین شمالی'},
  {district:5, name:'بلوار تعاون'},
  {district:5, name:'بلوار فردوس'},
  {district:5, name:'بولیوار'},
  {district:5, name:'پونک'},
  {district:5, name:'پیامبر'},
  {district:5, name:'جنت آباد'},
  {district:5, name:'سازمان برنامه'},
  {district:5, name:'ستاری'},
  {district:5, name:'سردار جنگل'},
  {district:5, name:'سولقان'},
  {district:5, name:'شهر زیبا'},
  {district:5, name:'شهران'},
  {district:5, name:'شهرک اکباتان'},
  {district:5, name:'شهید مهدی باکری'},

  {district:6, name:'نجات اللهی'},
  {district:6, name:'ایرانشهر'},
  {district:6, name:'پارک لاله'},
  {district:6, name:'کشاورز غربی'},
  {district:6, name:'نصرت'},
  {district:6, name:'۱۶آذر'},
  {district:6, name:'سنایی'},
  {district:6, name:'بهجت آباد'},
  {district:6, name:'عباس آباد'},
  {district:6, name:'قزل قلعه'},
  {district:6, name:'سیندخت'},
  {district:6, name:'گلها'},
  {district:6, name:'شیراز جنوبی'},
  {district:6, name:'گاندی'},
  {district:6, name:'ساعی'},
  {district:6, name:'یوسف آباد'},
  {district:6, name:'جهاد'},
  {district:6, name:'جنت'},
  {district:6, name:'آرژانتین'},
  {district:6, name:'اتوبان همت'},
  {district:6, name:'اسکندری'},
  {district:6, name:'امیر آباد'},
  {district:6, name:'بلوار کشاورز'},
  {district:6, name:'توانیر'},
  {district:6, name:'جمال زاده'},
  {district:6, name:'حافظ'},
  {district:6, name:'زرتشت'},
  {district:6, name:'طالقانی'},
  {district:6, name:'فاطمی'},
  {district:6, name:'فلسطین'},
  {district:6, name:'میدان انقلاب اسلامی'},
  {district:6, name:'میدان ولیعصر'},
  {district:6, name:'وزراء'},
  {district:6, name:'کارگر شمالی'},
  {district:6, name:'کردستان'},
  {district:6, name:'کریم خان'},

  {district:7, name:'شارق الف'},
  {district:7, name:'دهقان'},
  {district:7, name:'شارق ب'},
  {district:7, name:'گرگان'},
  {district:7, name:'نظام آباد'},
  {district:7, name:'خواجه نصیر و حقوقی'},
  {district:7, name:'خواجه نظام شرقی'},
  {district:7, name:'خواجه نظام غربی'},
  {district:7, name:'کاج'},
  {district:7, name:'امجدیه خاقانی'},
  {district:7, name:'بهار'},
  {district:7, name:'سهروردی باغ صبا'},
  {district:7, name:'شهیدقندی- نیلوفر'},
  {district:7, name:'عباس آباد- اندیشه'},
  {district:7, name:'حشمتیه'},
  {district:7, name:'دبستان'},
  {district:7, name:'ارامنه الف'},
  {district:7, name:'ارامنه ب'},
  {district:7, name:'قصر'},
  {district:7, name:'آپادانا'},
  {district:7, name:'امام حسین'},
  {district:7, name:'انقلاب'},
  {district:7, name:'خواجه نظام'},
  {district:7, name:'سرباز'},
  {district:7, name:'سهروردی'},
  {district:7, name:'شریعتی'},
  {district:7, name:'شهید مدنی'},
  {district:7, name:'شیخ صفی'},
  {district:7, name:'عباس آباد'},
  {district:7, name:'مدنی'},
  {district:7, name:'مرودشت'},
  {district:7, name:'مطهری'},
  {district:7, name:'مفتح جنوبی'},
  {district:7, name:'هفت تیر'},

  {district:8, name:'تهرانپارس'},
  {district:8, name:'دردشت'},
  {district:8, name:'مدائن'},
  {district:8, name:'هفت حوض'},
  {district:8, name:'فدک'},
  {district:8, name:'زرکش'},
  {district:8, name:'نارمک'},
  {district:8, name:'مجیدیه'},
  {district:8, name:'کرمان'},
  {district:8, name:'لشگر شرقی'},
  {district:8, name:'لشگر غربی'},
  {district:8, name:'وحیدیه'},
  {district:8, name:'تسلیحات'},
  {district:8, name:'جشنواره'},
  {district:8, name:'سبلان'},

  {district:9, name:'استادمعین'},
  {district:9, name:'دکتر هوشیار'},
  {district:9, name:'شهید دستغیب'},
  {district:9, name:'فتح'},
  {district:9, name:'امامزاده عبداله'},
  {district:9, name:'شمشیری'},
  {district:9, name:'سرآسیاب مهرآباد'},
  {district:9, name:'مهرآبادجنوبی'},
  {district:9, name:'استاد معین'},
  {district:9, name:'سی متری جی'},
  {district:9, name:'طوس'},
  {district:9, name:'مهر آباد جنوبی'},
  {district:9, name:'مهرآباد'},
  {district:9, name:'امامزاده عبدالله'},
  {district:9, name:'فتح – صنعتی'},

  {district:10, name:'بریانک'},
  {district:10, name:'سلیمانی تیموری'},
  {district:10, name:'شبیری جی'},
  {district:10, name:'هفت چنار'},
  {district:10, name:'سلسبیل جنوبی'},
  {district:10, name:'کارون جنوبی'},
  {district:10, name:'هاشمی'},
  {district:10, name:'زنجان جنوبی'},
  {district:10, name:'سلسبیل شمالی'},
  {district:10, name:'کارون شمالی'},
  {district:10, name:'آذربایجان'},
  {district:10, name:'آزادی'},
  {district:10, name:'امام خمینی'},
  {district:10, name:'جیحون'},
  {district:10, name:'حسام الدین'},
  {district:10, name:'خوش'},
  {district:10, name:'دامپزشکی'},
  {district:10, name:'رودکی'},
  {district:10, name:'سینا'},
  {district:10, name:'قصرالدشت'},
  {district:10, name:'مالک اشتر'},
  {district:10, name:'نواب'},
  {district:10, name:'کارون'},
  {district:10, name:'کمیل'},

  {district:11, name:'شیخ هادی'},
  {district:11, name:'انقلاب'},
  {district:11, name:'امیریه ( فرهنگ )'},
  {district:11, name:'فروزش'},
  {district:11, name:'قلمستان'},
  {district:11, name:'منیریه'},
  {district:11, name:'حشمت الدوله – جمالزاده'},
  {district:11, name:'اسکندری'},
  {district:11, name:'دخانیات'},
  {district:11, name:'مخصوص'},
  {district:11, name:'جمهوری'},
  {district:11, name:'حر'},
  {district:11, name:'انبار نفت'},
  {district:11, name:'آگاهی'},
  {district:11, name:'راه آهن'},
  {district:11, name:'عباسی'},
  {district:11, name:'هلال احمر'},
  {district:11, name:'ابوسعید'},
  {district:11, name:'اسکندری جنوبی'},
  {district:11, name:'پاستور'},
  {district:11, name:'حسن آباد'},
  {district:11, name:'گمرک'},
  {district:11, name:'وحدت اسلامی'},
  {district:11, name:'ولیعصر'},
  {district:11, name:'کارگر جنوبی'},
  {district:11, name:'کاشان'},

  {district:12, name:'بهارستان'},
  {district:12, name:'فردوسی'},
  {district:12, name:'امامزاده یحیی'},
  {district:12, name:'پامنار'},
  {district:12, name:'بازار'},
  {district:12, name:'سنگلج'},
  {district:12, name:'تختی'},
  {district:12, name:'هرندی'},
  {district:12, name:'آبشار'},
  {district:12, name:'قیام'},
  {district:12, name:'کوثر'},
  {district:12, name:'ایران'},
  {district:12, name:'دروازه شمیران'},
  {district:12, name:'امین حضور'},
  {district:12, name:'پانزده خرداد'},
  {district:12, name:'پیچ شمیران'},
  {district:12, name:'خراسان'},
  {district:12, name:'ری'},
  {district:12, name:'سعدی'},
  {district:12, name:'لاله زارنو'},
  {district:12, name:'مولوی'},
  {district:12, name:'میدان قیام'},

  {district:13, name:'صفا'},
  {district:13, name:'شهید اسدی'},
  {district:13, name:'زاهد گیلانی'},
  {district:13, name:'اشراقی'},
  {district:13, name:'دهقان'},
  {district:13, name:'نیروی هوایی'},
  {district:13, name:'پیروزی'},
  {district:13, name:'حافظیه'},
  {district:13, name:'امامت'},
  {district:13, name:'شورا'},
  {district:13, name:'آشتیانی'},
  {district:13, name:'زینبیه'},
  {district:13, name:'سرخه حصار'},
  {district:13, name:'تهران نو'},
  {district:13, name:'دماوند'},
  {district:13, name:'نیرو هوایی'},

  {district:14, name:'شکوفه'},
  {district:14, name:'چهارصد دستگاه'},
  {district:14, name:'جابری'},
  {district:14, name:'دژکام'},
  {district:14, name:'شاهین'},
  {district:14, name:'مینای شمالی'},
  {district:14, name:'نیکنام'},
  {district:14, name:'آهنگران'},
  {district:14, name:'بروجردی'},
  {district:14, name:'صد دستگاه'},
  {district:14, name:'فرزانه'},
  {district:14, name:'سر آسیب دولاب'},
  {district:14, name:'شیوا'},
  {district:14, name:'نبی اکرم (ص)'},
  {district:14, name:'شهرابی ( قیام )'},
  {district:14, name:'شکیب'},
  {district:14, name:'پرستار'},
  {district:14, name:'سیزده آبان'},
  {district:14, name:'ابوذر'},
  {district:14, name:'تاکسیرانی'},
  {district:14, name:'مینای جنوبی'},
  {district:14, name:'دولاب'},
  {district:14, name:'خاوران'},
  {district:14, name:'آهنگ شرقی'},
  {district:14, name:'آهنگ'},
  {district:14, name:'قصر فیروزه'},
  {district:14, name:'اتوبان محلاتی'},
  {district:14, name:'افراسیابی شمالی'},
  {district:14, name:'اندرزگو'},
  {district:14, name:'پاسدارگمنام'},
  {district:14, name:'شهید محلاتی'},
  {district:14, name:'فلاح'},
  {district:14, name:'نبرد'},
  {district:14, name:'هفده شهریور'},

  {district:15, name:'مظاهری'},
  {district:15, name:'مینابی'},
  {district:15, name:'بیسیم'},
  {district:15, name:'شوش'},
  {district:15, name:'طیب'},
  {district:15, name:'مطهری'},
  {district:15, name:'ابوذر'},
  {district:15, name:'هاشم آباد'},
  {district:15, name:'اتابک'},
  {district:15, name:'شهید بروجردی'},
  {district:15, name:'کیانشهر شمالی'},
  {district:15, name:'کیانشهر جنوبی'},
  {district:15, name:'رضویه'},
  {district:15, name:'مشیریه'},
  {district:15, name:'افسریه شمالی'},
  {district:15, name:'افسریه جنوبی'},
  {district:15, name:'مسعودیه'},
  {district:15, name:'والفجر'},
  {district:15, name:'قیامدشت'},
  {district:15, name:'خاورشهر'},
  {district:15, name:'آهنگ'},
  {district:15, name:'اتوبان بعثت'},
  {district:15, name:'افسریه'},
  {district:15, name:'خاوران'},
  {district:15, name:'مشیریه'},

  {district:16, name:'جوادیه'},
  {district:16, name:'نازی آباد'},
  {district:16, name:'خزانه'},
  {district:16, name:'شهرک بعثت'},
  {district:16, name:'علی آباد شمالی'},
  {district:16, name:'یاخچی آباد و چهارصد دستگاه'},
  {district:16, name:'تختی'},
  {district:16, name:'علی آباد جنوبی'},
  {district:16, name:'باغ آذری'},
  {district:16, name:'راه آهن'},
  {district:16, name:'رجایی'},
  {district:16, name:'هلال احمر'},
  {district:16, name:'یاخچی آباد'},

  {district:17, name:'ابوذر غربی'},
  {district:17, name:'آذری'},
  {district:17, name:'امامزاده حسن(ع)'},
  {district:17, name:'یافت آباد'},
  {district:17, name:'جلیلی'},
  {district:17, name:'زهتابی'},
  {district:17, name:'زمزم'},
  {district:17, name:'سجاد'},
  {district:17, name:'گلچین'},
  {district:17, name:'وصفنارد'},
  {district:17, name:'ابوذر شرقی'},
  {district:17, name:'باغ خزانه'},
  {district:17, name:'بلورسازی'},
  {district:17, name:'مقدم'},
  {district:17, name:'ابوذر'},
  {district:17, name:'امام زاده حسن'},
  {district:17, name:'قزوین'},
  {district:17, name:'قلعه مرغی'},
  {district:17, name:'میدان بهاران'},

  {district:18, name:'فردوس'},
  {district:18, name:'تولیدارو'},
  {district:18, name:'بهداشت'},
  {district:18, name:'ولیعصر شمالی'},
  {district:18, name:'رجائی'},
  {district:18, name:'ولیعصر جنوبی'},
  {district:18, name:'صادقیه'},
  {district:18, name:'صاحب الزمان'},
  {district:18, name:'یافت آباد جنوبی'},
  {district:18, name:'یافت آباد شمالی'},
  {district:18, name:'شاد آباد'},
  {district:18, name:'هفده شهریور'},
  {district:18, name:'امام خمینی (ره )'},
  {district:18, name:'شمس آباد'},
  {district:18, name:'خلیج فارس شمالی'},
  {district:18, name:'خلیج فارس جنوبی'},
  {district:18, name:'اتوبان آزادگان'},
  {district:18, name:'خلیج فارس'},
  {district:18, name:'سعید آباد'},
  {district:18, name:'شهرک صاحب الزمان'},
  {district:18, name:'شهرک ولیعصر'},

  {district:19, name:'خانی آباد نو شمالی'},
  {district:19, name:'اسفندیاری و بستان'},
  {district:19, name:'بهمنیار'},
  {district:19, name:'خانی آباد نو جنوبی'},
  {district:19, name:'شریعتی جنوبی'},
  {district:19, name:'شریعتی شمالی'},
  {district:19, name:'شکوفه جنوبی'},
  {district:19, name:'شکوفه شمالی'},
  {district:19, name:'نعمت آباد'},
  {district:19, name:'دولت خواه'},
  {district:19, name:'اسماعیل آباد'},
  {district:19, name:'شهید کاظمی'},
  {district:19, name:'رسالت'},
  {district:19, name:'خانی آباد نو'},
  {district:19, name:'عبدل آباد'},

  {district:20, name:'اقدسیه'},
  {district:20, name:'صفائیه'},
  {district:20, name:'ظهیر آباد'},
  {district:20, name:'غیوری'},
  {district:20, name:'جوانمرد'},
  {district:20, name:'حمزه آباد'},
  {district:20, name:'دیلمان'},
  {district:20, name:'فیروزآبادی'},
  {district:20, name:'منصوریه'},
  {district:20, name:'۱۳آبان'},
  {district:20, name:'دولت اباد'},
  {district:20, name:'شهادت'},
  {district:20, name:'استخر'},
  {district:20, name:'بهشتی'},
  {district:20, name:'سرتخت'},
  {district:20, name:'علائین'},
  {district:20, name:'نفر آباد'},
  {district:20, name:'ولی آباد'},
  {district:20, name:'امین آباد'},
  {district:20, name:'تقی آباد'},
  {district:20, name:'نظامی'},
  {district:20, name:'عباس آباد'},
  {district:20, name:'کهریزک'},

  {district:21, name:'شهرک دریا'},
  {district:21, name:'تهرانسر غربی'},
  {district:21, name:'تهرانسر شرقی'},
  {district:21, name:'باشگاه نفت'},
  {district:21, name:'تهرانسر مرکزی'},
  {district:21, name:'شهرک پاسداران'},
  {district:21, name:'تهرانسر شمالی'},
  {district:21, name:'شهرک آزادی'},
  {district:21, name:'شهرک فرهنگیان'},
  {district:21, name:'شهرک استقلال'},
  {district:21, name:'شهرک دانشگاه'},
  {district:21, name:'چیتگر شمالی'},
  {district:21, name:'چیتگر جنوبی (شهرک ۲۲ بهمن)'},
  {district:21, name:'ویلا شهر'},
  {district:21, name:'وردآورد'},
  {district:21, name:'شهرک غزالی'},
  {district:21, name:'شهرک شهرداری'},
  {district:21, name:'اتوبان تهران کرج'},
  {district:21, name:'بزرگراه فتح'},
  {district:21, name:'تهرانسر'},
  {district:21, name:'شهرک ۲۲بهمن'},
  {district:21, name:'شهرک دانشگاه شریف'},

  {district:22, name:'دهکده المپیک'},
  {district:22, name:'زیبا دشت بالا'},
  {district:22, name:'گلستان شرقی'},
  {district:22, name:'زیبادشت پائین'},
  {district:22, name:'شریف'},
  {district:22, name:'گلستان غربی'},
  {district:22, name:'امید – دژبان'},
  {district:22, name:'شهید باقری'},
  {district:22, name:'آزادشهر'},
  {district:22, name:'پیکان شهر'},
  {district:22, name:'دریاچه چیتگر'},
  {district:22, name:'شهرک راه آهن – شهرک گلستان'},

]


export const giveMeNeighbourhoods = () => {
  return new Promise( (res,rej) => {
    setTimeout(() => {
      res(Object.assign([], neighbourhoods))
    }, delay);
  })
}
